### ISSUE TITLE
Get ownership or clone the custom google search engine

### ISSUE THREAD

**Issue by mgrojo** [thindil/adasearch#1]
Hi @thindil,

I'm taking care of your archived project thindil/adasearch. You can see my update on this page. I appreciate any feedback about it, if you have any.

This issue is mainly for properly taking a fork, not only of the HTML, but also of the custom Google engine. Is this something that can be transferred or exported to be cloned, so it is now under my control?

**Comment by thindil** [comment]
Hello.

Thank you for taking care of it. If you want, I can transfer the old project to you, so no fork would be needed. 😄 

About custom search engine. I'm not sure. I see I can add a new owner to it, perhaps then you will be able to manage it. For this, I will need any of your emails. When this won't work, I will give you all needed information about the search engine configuration.

**Comment by mgrojo** [comment]
> Hello.
> 
> Thank you for taking care of it. If you want, I can transfer the old project to you, so no fork would be needed. 😄

I don't mind it saying it's a fork, it's like a homage to you :smile:, and in any case, that could be removed, as I did for https://github.com/mgrojo/ASFML because the previous author was disappeared. That can be asked to GitHub, but now that I've learned more about Git I guess you can also do it, by just cloning from the original and then creating a new project from scratch and populating it with that cloned repository. I guess the transfer would do the same? Or would it still be under your path? In that case, I prefer to keep it as a fork, which can later be converted into a main repository.

> 
> About custom search engine. I'm not sure. I see I can add a new owner to it, perhaps then you will be able to manage it. For this, I will need any of your emails. When this won't work, I will give you all needed information about the search engine configuration.

Let's try then with the new owner. You can use mgrojo at gmail.com.

**Comment by thindil** [comment]
About fork, no problem here for me. 😄 

About ownership: I added the email, you have now to verify your account there. The full address to the settings is: https://programmablesearchengine.google.com/controlpanel/overview?cx=009829025445605706198%3A-dt42nxzgi8

If everything will be good there, I will remove myself from the list of owners (I hope it is possible). If you have any questions, feel free to ask. I hope I remember how to set things there. 😉

**Comment by mgrojo** [comment]
> About fork, no problem here for me. 😄

I've been reading about the [transfer of ownership](https://docs.github.com/repositories/creating-and-managing-repositories/transferring-a-repository), and it seems the better way to go, because it will leave a redirection behind, so any link that might there be out there, would redirect to the new location. There's no redirection for the github page, though, so I guess it will simply disappear.

I've renamed this repository so we can try the transfer and leave it in "mgrojo/adasearch".

> 
> About ownership: I added the email, you have now to verify your account there. The full address to the settings is: https://programmablesearchengine.google.com/controlpanel/overview?cx=009829025445605706198%3A-dt42nxzgi8

Perfect, thanks. I'm now in.

> 
> If everything will be good there, I will remove myself from the list of owners (I hope it is possible). If you have any questions, feel free to ask. I hope I remember how to set things there. 😉

For the moment, the configuration seems straightforward. I have a doubt already, did you try with the included and excluded pages to improve results? It seems as best as it could be, nevertheless, so maybe not useful.

**Comment by thindil** [comment]
Transferring ownership, I was trying to do it, and I got error: 

*mgrojo already has a repository in the thindil/adasearch network*

My guess, you have to delete this fork if we want to transfer it to you.  That can make following this issue a bit harder, unless you reopen it on the original repo.  I just "unarchived" it for a moment.😉 

Including/excluding, no, I didn't play with it. I never felt like I need it. But last time I was setting it a few years ago, before AI bonanza. Today, it can be a good idea to remove some fake pages, if they appear somewhere in results.

**Comment by mgrojo** [comment]
> My guess, you have to delete this fork if we want to transfer it to you. That can make following this issue a bit harder, unless you reopen it on the original repo. I just "unarchived" it for a moment.😉

It cannot be transferred to another user's repo, so I've created this temporary issue only for storing the issue. I'll delete now adasearch_fork.

**Comment by mgrojo** [comment]
adasearch_fork now kept safe in local clone and deleted in GitHub. Let's try now the ownership transfer. I guess it should work.

**Comment by thindil** [comment]
Ok, seems like it works. 😄 It awaiting now for your confirmation.

**Comment by mgrojo** [comment]
Great! But maybe it's queued, because I haven't received any notification. Or am I supposed to check somewhere?

**Comment by mgrojo** [comment]
Oh, I missed the email, it was immediate. Now it is in https://github.com/mgrojo/adasearch, I've already pushed my changes, https://github.com/thindil/adasearch is redirecting to it, and it's already live at https://mgrojo.github.io/adasearch/.

Thanks a lot for the support.

**Comment by thindil** [comment]
No problem, have fun and take care. 😄 In a few days, if you won't need my help with the custom search engine, I will remove myself from there. Or feel free to remove me. 😁 

I think you can close this issue as solved.

**Comment by mgrojo** [comment]
Great. Have a nice day.
